#!/bin/bash

NOW=`date "+%Y%m%d"`
BACKUP_DIR="/var/backups"
DAYS_AGO=5

# Backup
#
/usr/bin/mongodump --journal --out ${BACKUP_DIR}/mongodump-${NOW}

# Cleanup
#
find ${BACKUP_DIR}/mongodump-* -maxdepth 0 -type d -mtime ${DAYS_AGO} -exec rm -rf '{}' ';'
